//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalServices.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        public int id_cita { get; set; }
        public int id_evento { get; set; }
        public Nullable<System.TimeSpan> hora_cita { get; set; }
        public string especialidad { get; set; }
        public string motivo { get; set; }
        public string estado_cita { get; set; }

        [JsonIgnore]

        public virtual EventosMedico EventosMedico { get; set; }
    }
}
