//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalServices.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hospital_dbEntities : DbContext
    {
        public hospital_dbEntities()
            : base("name=hospital_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alta> Altas { get; set; }
        public virtual DbSet<Cita> Citas { get; set; }
        public virtual DbSet<DetallesFormula> DetallesFormulas { get; set; }
        public virtual DbSet<EventosMedico> EventosMedicos { get; set; }
        public virtual DbSet<Facturacione> Facturaciones { get; set; }
        public virtual DbSet<Formula> Formulas { get; set; }
        public virtual DbSet<Habitacione> Habitaciones { get; set; }
        public virtual DbSet<Hospitalizacione> Hospitalizaciones { get; set; }
        public virtual DbSet<Medicamento> Medicamentos { get; set; }
        public virtual DbSet<Medico> Medicos { get; set; }
        public virtual DbSet<Paciente> Pacientes { get; set; }
        public virtual DbSet<Pago> Pagos { get; set; }
        public virtual DbSet<Pais> Paises { get; set; }
        public virtual DbSet<Persona> Personas { get; set; }
        public virtual DbSet<TipoHabitacione> TipoHabitaciones { get; set; }
        public virtual DbSet<Urgencia> Urgencias { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
