//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallesFormula
    {
        public int id_detalle_formula { get; set; }
        public Nullable<int> cantidad { get; set; }
        public string dosis { get; set; }
    
        public virtual Formula Formula { get; set; }
        public virtual Medicamento Medicamento { get; set; }
    }
}
