//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalServices.Models
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;

    public partial class Facturacione
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Facturacione()
        {
            this.Pagos = new HashSet<Pago>();
        }
    
        public int id_factura { get; set; }
        public int id_paciente { get; set; }
        public int id_evento { get; set; }
        public double total { get; set; }
        public string metodo_pago { get; set; }
        public Nullable<System.DateTime> fecha_emision { get; set; }
        public string estado_pago { get; set; }

        [JsonIgnore]
        public virtual EventosMedico EventosMedico { get; set; }

        [JsonIgnore]
        public virtual Paciente Paciente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pago> Pagos { get; set; }
    }
}
